# Clock signal
set_property PACKAGE_PIN W5 [get_ports CLK100MHZ]
	set_property IOSTANDARD LVCMOS33 [get_ports CLK100MHZ]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLK100MHZ]

set_property PACKAGE_PIN J1 [get_ports {reset_0}]
set_property IOSTANDARD LVCMOS33 [get_ports {reset_0}]

##Buttons
set_property PACKAGE_PIN U18 [get_ports buttons[4]]
  set_property IOSTANDARD LVCMOS33 [get_ports buttons[4]]
set_property PACKAGE_PIN T18 [get_ports buttons[0]]
  set_property IOSTANDARD LVCMOS33 [get_ports buttons[0]]
set_property PACKAGE_PIN W19 [get_ports buttons[1]]
	set_property IOSTANDARD LVCMOS33 [get_ports buttons[1]]
set_property PACKAGE_PIN T17 [get_ports buttons[2]]
	set_property IOSTANDARD LVCMOS33 [get_ports buttons[2]]
set_property PACKAGE_PIN U17 [get_ports buttons[3]]
  set_property IOSTANDARD LVCMOS33 [get_ports buttons[3]]

# switches
set_property PACKAGE_PIN V17 [get_ports {switches[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {switches[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[7]}]
set_property PACKAGE_PIN V2 [get_ports {switches[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[8]}]
set_property PACKAGE_PIN T3 [get_ports {switches[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[9]}]
set_property PACKAGE_PIN T2 [get_ports {switches[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[10]}]
set_property PACKAGE_PIN R3 [get_ports {switches[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[11]}]
set_property PACKAGE_PIN W2 [get_ports {switches[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[12]}]
set_property PACKAGE_PIN U1 [get_ports {switches[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[13]}]
set_property PACKAGE_PIN T1 [get_ports {switches[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {switches[14]}]
set_property PACKAGE_PIN R2 [get_ports {switches[15]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {switches[15]}]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LED_0[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED_0[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED_0[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED_0[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED_0[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED_0[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED_0[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED_0[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED_0[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED_0[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED_0[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED_0[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED_0[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED_0[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED_0[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED_0[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[15]}]

##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports usb_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_txd]
set_property PACKAGE_PIN A18 [get_ports usb_uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_rxd]
