# Clock signal
set_property PACKAGE_PIN W5 [get_ports sys_clock]
	set_property IOSTANDARD LVCMOS33 [get_ports sys_clock]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports sys_clock]

##Buttons
set_property PACKAGE_PIN U18 [get_ports reset_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_0]


##USB-RS232 Interface
set_property PACKAGE_PIN B18 [get_ports usb_uart_txd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_txd]
set_property PACKAGE_PIN A18 [get_ports usb_uart_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports usb_uart_rxd]

# LEDs
set_property PACKAGE_PIN U16 [get_ports {LED_0[0]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[0]}]
set_property PACKAGE_PIN E19 [get_ports {LED_0[1]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[1]}]
set_property PACKAGE_PIN U19 [get_ports {LED_0[2]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[2]}]
set_property PACKAGE_PIN V19 [get_ports {LED_0[3]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[3]}]
set_property PACKAGE_PIN W18 [get_ports {LED_0[4]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[4]}]
set_property PACKAGE_PIN U15 [get_ports {LED_0[5]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[5]}]
set_property PACKAGE_PIN U14 [get_ports {LED_0[6]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[6]}]
set_property PACKAGE_PIN V14 [get_ports {LED_0[7]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[7]}]
set_property PACKAGE_PIN V13 [get_ports {LED_0[8]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[8]}]
set_property PACKAGE_PIN V3 [get_ports {LED_0[9]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[9]}]
set_property PACKAGE_PIN W3 [get_ports {LED_0[10]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[10]}]
set_property PACKAGE_PIN U3 [get_ports {LED_0[11]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[11]}]
set_property PACKAGE_PIN P3 [get_ports {LED_0[12]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[12]}]
set_property PACKAGE_PIN N3 [get_ports {LED_0[13]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[13]}]
set_property PACKAGE_PIN P1 [get_ports {LED_0[14]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[14]}]
set_property PACKAGE_PIN L1 [get_ports {LED_0[15]}]
	set_property IOSTANDARD LVCMOS33 [get_ports {LED_0[15]}]
